/**:
    ros__parameters:
      global_frame_id: "map"
      odom_frame_id: "odom"
      base_frame_id: "base_link"
      registration_method: "NDT"
      ndt_resolution: 3.0
      ndt_step_size: 0.4
      transform_epsilon: 0.01
      voxel_leaf_size: 1.0
      scan_max_range: 100.0
      scan_min_range: 2.0
      scan_period: 0.5
      use_pcd_map: true
      map_path: "/home/robot/autoware_universe/autoware_map/gazebo_map/pointcloud_map.pcd"
      set_initial_pose: true
      initial_pose_x: 0.0
      initial_pose_y: 0.0
      initial_pose_z: 0.0
      initial_pose_qx: 0.0
      initial_pose_qy: 0.0
      initial_pose_qz: 0.0
      initial_pose_qw: 1.0
      use_odom: false
      use_imu: false
      enable_debug: false